//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagerWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.TimeSpan ReservationTime { get; set; }
        public int PartySize { get; set; }
        public string ReservationDetails { get; set; }
        public int ClientId { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
